; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "tx"
#define MyAppVersion "1.4.0"
#define MyAppPublisher "yoy.be"
#define MyAppURL "http://yoy.be/tx.html"
#define MyAppExeName "txSvc.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{CA98A6F4-3D6A-49DF-BD84-C902C02A8001}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName=C:\txService
DisableProgramGroupPage=yes
LicenseFile=LICENSE
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=txServiceSetup
SetupIconFile=rel_2\favicon.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "startsvc"; Description: "Start the service after installing"; GroupDescription: "Service"
Name: "openweb"; Description: "Start the website in a browser"; GroupDescription: "Service"

[Files]
Source: "rel_2\*"; Excludes: "tx.db"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs restartreplace
Source: "rel_2\tx.db"; DestDir: "{app}"; Flags: onlyifdoesntexist uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Run]
Filename: "{app}\SQLiteBatch.exe"; WorkingDir: "{app}"; Parameters: "tx.db -I tx_UPGRADE.sql"; Description: "Prepare database..."; Flags: runhidden
Filename: "{app}\{#MyAppExeName}"; Parameters: "/install /silent"; Description: "Registering service..."
Filename: "{sys}\net.exe"; Parameters: "start tx"; Description: "Starting service..."; Flags: runhidden; Tasks: startsvc
Filename: "{sys}\cmd.exe"; Parameters: "/c start http://localhost/"; Description: "Opening website..."; Flags: runhidden; Tasks: openweb

[UninstallRun]
Filename: "{sys}\net.exe"; Parameters: "stop tx"; Flags: runhidden; RunOnceId: "txSvcStop"
Filename: "{sys}\taskkill.exe"; Parameters: "/f /im txSvc.exe"; Flags: skipifdoesntexist runhidden; RunOnceId: "txUninstKill"
Filename: "{app}\{#MyAppExeName}"; Parameters: "/uninstall /silent"; RunOnceId: "txSvcUninst"
